# This file was generated by GoReleaser. DO NOT EDIT.
cask "flashtui" do
  version "0.1.0"

  on_linux do
    on_arm do
      sha256 "04a1766c0f47cc807c4493925d6c034e2827f8a52d304f113acaf6de49e9e5a9"
      url "https://github.com/susamn/flashtui/releases/download/v#{version}/flashtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84a19a67118f95962a9ed63cfc19fdfdc2321f706677e426810c5d500eeb88e2"
      url "https://github.com/susamn/flashtui/releases/download/v#{version}/flashtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flashtui"
  desc "Terminal UI for writing OS images to removable drives"
  homepage "https://github.com/susamn/flashtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flashtui"

  # No zap stanza required

  caveats <<~EOS
    flashtui drives system tools Homebrew does not package. Install them
    with your distribution's package manager:

      Arch     sudo pacman -S util-linux systemd polkit
      Debian   sudo apt install util-linux udev policykit-1
      Fedora   sudo dnf install util-linux systemd-udev polkit

    It needs lsblk, udevadm and partprobe to enumerate drives, and
    pkexec to acquire the privileges writing a block device requires.
    Compressed images additionally need xz, gzip or zstd on PATH,
    whichever formats you intend to write.

    Do not reach for `brew install util-linux` here. Homebrew's lsblk is
    not linked against libudev and silently reports no filesystem type,
    label or partition table, which would leave the drive readout and
    the safety guard blank. flashtui prefers /usr/bin/lsblk for exactly
    this reason -- keep the distribution's copy installed.
  EOS
end
