# This file was generated by GoReleaser. DO NOT EDIT.
cask "lshwtui" do
  version "0.1.0"

  on_linux do
    on_arm do
      sha256 "4e4305881728db556695b89011bd8d21b756e9d9bffedc18c08a28b5746593f1"
      url "https://github.com/susamn/lshwtui/releases/download/v#{version}/lshwtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f81555d8dfc3af41a79e5189468befaa7af5545dd18124866dd29f79a267a20"
      url "https://github.com/susamn/lshwtui/releases/download/v#{version}/lshwtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lshwtui"
  desc "Vim-navigable terminal UI for lshw"
  homepage "https://github.com/susamn/lshwtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lshwtui"

  caveats <<~EOS
    lshwtui needs the lshw binary, which Homebrew does not package:

      Arch     sudo pacman -S lshw
      Debian   sudo apt install lshw
      Fedora   sudo dnf install lshw

    lshw only reports the complete hardware tree as root. Run lshwtui
    normally and press R to re-run it through sudo, doas or pkexec.

    Device icons need a Nerd Font. Without one, run: lshwtui --no-glyphs
  EOS
end
