# This file was generated by GoReleaser. DO NOT EDIT.
cask "mpdtui" do
  version "3.2.1"

  on_macos do
    on_arm do
      sha256 "66aaf3df49ea9d8efc1ca0d6b0487e4d810666e91813ad3ba7a3ddce5b03517b"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5c5d58b33982cfbf62afbbcae4242275c5f4acd16246faaa21fc3b6e5bcbe46"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1742db2ea69910204c87d19d5e2abf16fe800ac117f51254ba1a25c3a95b4a7b"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb074838b319f21954a6d5df91f8dfb4c61202fd522b8b07211efdd4fb44c475"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mpdtui"
  desc "Lazygit-style terminal UI for MPD (Music Player Daemon)"
  homepage "https://github.com/susamn/mpdtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mpdtui"

  # No zap stanza required

  caveats <<~EOS
    mpdtui is a client -- it needs an MPD server to talk to.

      brew      brew install mpd && brew services start mpd
      Arch      sudo pacman -S mpd
      Debian    sudo apt install mpd

    It connects to 127.0.0.1:6600 by default; override with MPD_HOST
    and MPD_PORT.
  EOS
end
