# This file was generated by GoReleaser. DO NOT EDIT.
cask "mpdtui" do
  version "3.1.0"

  on_macos do
    on_arm do
      sha256 "7b1658dfea9cc06ea6d23a1f9be93f673720646c70ae834684627199c2e41313"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f8f4e65bf485b0054a6aa6c830207fdb272f71ac4f60a595db354d816c520a3"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "307b93f11a99b5526931d3e5a7e15079af69939a5f0c5e7bf0f6418a37d005f8"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8b1d2bc71b5d760d9b2f1dc7fdd8c2d87a8a5149d7e242c6157f57cdf4d58ea"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mpdtui"
  desc "Lazygit-style terminal UI for MPD (Music Player Daemon)"
  homepage "https://github.com/susamn/mpdtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mpdtui"

  # No zap stanza required

  caveats <<~EOS
    mpdtui is a client -- it needs an MPD server to talk to.

      brew      brew install mpd && brew services start mpd
      Arch      sudo pacman -S mpd
      Debian    sudo apt install mpd

    It connects to 127.0.0.1:6600 by default; override with MPD_HOST
    and MPD_PORT.
  EOS
end
