# This file was generated by GoReleaser. DO NOT EDIT.
cask "mpdtui" do
  version "3.2.0"

  on_macos do
    on_arm do
      sha256 "2e96f2268a124ae1f81e1659ecaa91bb98233986d03fbceaea3dd4fbcf935e57"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "39e4b1d8341cfd814d2f6be89544e01df93d7e1de58d5b084d6ea1fd4237ea64"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32b421abe3ff3dee297857b7e26028d68a8b279187e0f8f01b3864256d4d8ad1"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c6e154ed3c3ed3852f2b51034d3e58b609d17114443544be341d692bfa1d26f2"
      url "https://github.com/susamn/mpdtui/releases/download/v#{version}/mpdtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mpdtui"
  desc "Lazygit-style terminal UI for MPD (Music Player Daemon)"
  homepage "https://github.com/susamn/mpdtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mpdtui"

  # No zap stanza required

  caveats <<~EOS
    mpdtui is a client -- it needs an MPD server to talk to.

      brew      brew install mpd && brew services start mpd
      Arch      sudo pacman -S mpd
      Debian    sudo apt install mpd

    It connects to 127.0.0.1:6600 by default; override with MPD_HOST
    and MPD_PORT.
  EOS
end
